// Codegen entry — JSON Schema → packages/client/src/types.gen.ts.
//
// Reads the committed schemas under packages/server/proto/schemas/ and emits a
// single `types.gen.ts` for the SDK to consume. See ADR-0002.
//
// Run via `task gen:types` (or `bun run gen:types`); CI runs the same
// `bun packages/client/scripts/gen-types.ts` invocation as a smoke test.

import { readdirSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { compileFromFile } from "json-schema-to-typescript";

const HERE = dirname(fileURLToPath(import.meta.url));
const CLIENT_ROOT = resolve(HERE, "..");
const REPO_ROOT = resolve(CLIENT_ROOT, "..", "..");
const SCHEMAS_DIR = join(REPO_ROOT, "packages", "server", "proto", "schemas");
const OUT_FILE = join(CLIENT_ROOT, "src", "types.gen.ts");

const HEADER = [
  "// AUTO-GENERATED FROM packages/server/src/proto.rs",
  "// DO NOT EDIT THIS FILE BY HAND.",
  "// Re-generate via `task gen:types` (or `bun run gen:types`).",
  "",
  "",
].join("\n");

// json-schema-to-typescript replays `definitions` inline, so a schema like
// Info.schema.json (which references Capability via `#/definitions/Capability`)
// emits both `export type Capability` and `export interface Info`. Compiling
// each schema independently therefore duplicates `Capability`. Splitting the
// output into top-level declaration blocks and dropping repeats by name keeps
// the merged file unique without losing JSDoc.
function splitTopLevel(ts: string): string[] {
  const blocks: string[] = [];
  const text = ts.replace(/\r\n/g, "\n");
  let i = 0;
  while (i < text.length) {
    while (i < text.length && /\s/.test(text[i])) i++;
    if (i >= text.length) break;
    const start = i;

    if (text.startsWith("/**", i)) {
      const close = text.indexOf("*/", i);
      if (close < 0) break;
      i = close + 2;
      while (i < text.length && /\s/.test(text[i])) i++;
    }

    if (!text.startsWith("export ", i)) {
      i++;
      continue;
    }

    const head = text.slice(i).match(/^export (type|interface)\s+\w+/);
    if (!head) {
      i++;
      continue;
    }

    if (head[1] === "type") {
      // Type alias body may span multiple lines (e.g. untagged enums emit
      // `export type Foo = ({ a: ... } | { b: ... })`). Read until the next
      // top-level statement (a newline followed by `export `) or EOF, while
      // tracking bracket depth so braces inside the alias body don't terminate
      // the scan early.
      const eq = text.indexOf("=", i);
      if (eq < 0) {
        i++;
        continue;
      }
      let depth = 0;
      let j = eq + 1;
      while (j < text.length) {
        const ch = text[j];
        if (ch === "{" || ch === "(" || ch === "[") depth++;
        else if (ch === "}" || ch === ")" || ch === "]") depth--;
        else if (ch === "\n" && depth === 0) {
          let k = j + 1;
          while (k < text.length && text[k] !== "\n" && /\s/.test(text[k])) k++;
          if (k >= text.length || text.startsWith("export ", k)) {
            j++;
            break;
          }
        }
        j++;
      }
      i = j;
    } else {
      const open = text.indexOf("{", i);
      if (open < 0) break;
      let depth = 0;
      let j = open;
      while (j < text.length) {
        const ch = text[j];
        if (ch === "{") depth++;
        else if (ch === "}") {
          depth--;
          if (depth === 0) {
            j++;
            break;
          }
        }
        j++;
      }
      i = j;
    }

    blocks.push(text.slice(start, i).trimEnd());
  }
  return blocks;
}

function blockName(block: string): string | null {
  const m = block.match(/export (?:type|interface)\s+(\w+)/);
  return m ? m[1] : null;
}

export async function generate(): Promise<string> {
  const entries = readdirSync(SCHEMAS_DIR)
    .filter((f) => f.endsWith(".schema.json"))
    .sort();

  if (entries.length === 0) {
    throw new Error(`no *.schema.json found in ${SCHEMAS_DIR}; run gen-schemas first`);
  }

  const seen = new Set<string>();
  const parts: string[] = [];
  for (const entry of entries) {
    const ts = await compileFromFile(join(SCHEMAS_DIR, entry), {
      additionalProperties: false,
      bannerComment: "",
      format: false,
    });
    for (const block of splitTopLevel(ts)) {
      const name = blockName(block);
      if (!name || seen.has(name)) continue;
      seen.add(name);
      parts.push(block);
    }
  }

  const body = `${HEADER}${parts.join("\n\n")}\n`;
  await mkdir(dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, body, "utf8");
  return OUT_FILE;
}

if (import.meta.main) {
  const path = await generate();
  console.log(`wrote ${path}`);
}
